export const navigation = [
  { label: 'Platform', links: [['Payments', '/solutions/payments'], ['Bill payments', '/solutions/bill-payments'], ['Payouts & transfers', '/solutions/payouts'], ['For merchants', '/industries']] },
  { label: 'Company', links: [['About ReachPay', '/about'], ['Industries', '/industries'], ['Case studies', '/case-studies'], ['Leadership', '/leadership']] },
  { label: 'Resources', links: [['Insights', '/insights'], ['Careers', '/careers']] },
];

export const solutions = [
  { icon: '↗', title: 'Payments', slug: 'payments', body: 'A proposed overview for online payment acceptance, payment status and reconciliation. Supported methods and availability require confirmation against ReachPay’s provider agreements.' },
  { icon: '▦', title: 'Bill payments', slug: 'bill-payments', body: 'A proposed bill-payment experience covering supported billers and service categories. Only provider-enabled billers should be published.' },
  { icon: '⇄', title: 'Payouts & transfers', slug: 'payouts', body: 'A proposed merchant payout and transfer workflow with beneficiary controls, transaction references and status visibility. Availability is subject to authorized banking partners.' },
  { icon: '◫', title: 'Assisted commerce', slug: 'assisted-commerce', body: 'A proposed assisted-service experience for in-person and agent-supported customer journeys. Terminal availability and service coverage need business confirmation.' },
];

export const industries = [
  ['Retail & commerce', 'Payment acceptance, operational visibility and settlement workflows for merchants. Product fit and integrations need confirmation.'],
  ['Financial services', 'A technology layer for payment and bill-service journeys, subject to licensed partner availability and compliance review.'],
  ['Utilities & billers', 'Digital bill-payment journeys with biller coverage determined by an authorized network provider.'],
  ['Platforms & marketplaces', 'Potential tools for platforms to coordinate collections and merchant operations. Capabilities are subject to technical and commercial review.'],
];

export const insights = [
  { slug: 'clear-payment-status', category: 'Payments', title: 'Designing clear payment status experiences', date: 'Editorial draft', excerpt: 'A practical framework for showing what is known, what is pending, and what a customer should do next.', body: 'A useful payment status tells a person what has happened and what has not. Distinguish a request being created from a provider-confirmed outcome; explain what action, if any, is expected; and show a stable reference for support. Keep messages calm when a provider response is delayed, and avoid presenting pending funds as available. Product teams should agree on one state vocabulary across notifications, transaction history and support workflows.', placeholder: true },
  { slug: 'reconciliation-checklist', category: 'Operations', title: 'A reconciliation checklist for payment teams', date: 'Editorial draft', excerpt: 'The records and controls teams can compare when a payment provider and an internal system disagree.', body: 'Start with a stable transaction reference, then compare amount, currency, provider status and timestamps across records. Check whether the corresponding ledger movement exists and whether duplicate provider events were received. Record mismatches for review with enough context to investigate. Avoid silently changing historical entries; corrections should have a traceable explanation and an appropriate accounting record. The exact control framework depends on the organization and provider.', placeholder: true },
  { slug: 'beneficiary-data-care', category: 'Security', title: 'Protecting sensitive beneficiary information', date: 'Editorial draft', excerpt: 'Data minimization, role checks and audit trails belong in the design from the beginning.', body: 'Collect only the beneficiary details an approved service requires. Limit access to authorized roles, mask sensitive identifiers in ordinary views, protect data at rest and in transit, and retain an audit trail for sensitive changes. Step-up verification can help protect high-impact changes, but must be implemented with secure recovery and support processes. Legal and security teams should confirm retention, access and provider requirements before launch.', placeholder: true },
];

export const pages = {
  '/about': { title: 'About ReachPay', description: 'Company overview and mission — pending confirmation by ReachPay.', eyebrow: 'ABOUT REACHPAY', headline: 'Building clearer ways to move money.', intro: 'ReachPay is presented here as a financial technology company focused on payment and bill-service experiences. The company’s official history, operating locations, licenses, and mission statement must be supplied and approved before publication.', sections: [['What we are building', 'A considered payments experience brings together reliable infrastructure, transparent status and operational controls. ReachPay’s actual product scope and supported markets need internal confirmation.'], ['How we work', 'We aim to make complex financial workflows easier to understand while treating customer data, financial accuracy and partner requirements with care. This statement is proposed brand copy, not a verified operating commitment.']] },
  '/leadership': { title: 'Leadership', description: 'ReachPay leadership directory. Names and biographies require company confirmation.', eyebrow: 'LEADERSHIP', headline: 'People behind the work.', intro: 'Leadership profiles are intentionally omitted until ReachPay provides approved names, roles, biographies and photographs. No individuals or credentials have been invented.', sections: [['Share approved profiles', 'Add each leader’s approved name, title, short biography and image with their consent. Include only verifiable professional details.']] },
  '/case-studies': { title: 'Case studies', description: 'Customer stories and case studies — publication-ready examples require customer approval.', eyebrow: 'CUSTOMER STORIES', headline: 'Proof should come from the people who use it.', intro: 'No customer outcomes, testimonials or performance metrics are published here because ReachPay has not supplied approved customer evidence.', sections: [['What a case study should include', 'Customer-approved context, the challenge, implemented product capabilities, measurable results with methodology, and written permission to publish.']] },
  '/careers': { title: 'Careers', description: 'Explore opportunities at ReachPay. Open roles are not listed until confirmed by the company.', eyebrow: 'CAREERS', headline: 'Do thoughtful work that matters.', intro: 'Current openings and hiring locations have not been provided. Use this page to send an expression of interest; it is delivered only when the contact email integration is configured.', sections: [['A considered hiring process', 'ReachPay should add role descriptions, employment terms, location, accessibility information and a candidate privacy notice before advertising positions.']] },
  '/privacy': { title: 'Privacy policy', description: 'Privacy notice placeholder for ReachPay; legal review required before publication.', eyebrow: 'LEGAL', headline: 'Privacy notice', intro: 'This draft is a publishing scaffold, not legal advice or an approved privacy policy. ReachPay must have counsel replace it with a notice reflecting its actual data practices, entities, jurisdictions, processors and retention periods.', sections: [['Information and purpose', 'Describe exactly what personal data is collected, why it is used, the legal basis where applicable, and which service providers receive it.'], ['Your choices and rights', 'Provide the correct contact channel and jurisdiction-specific rights, response timelines, complaint route, retention schedule and effective date.'], ['Contact', 'Replace this placeholder with ReachPay’s registered entity name and privacy contact before publication.']] },
  '/terms': { title: 'Terms of use', description: 'Terms of use placeholder for ReachPay; legal review required before publication.', eyebrow: 'LEGAL', headline: 'Terms of use', intro: 'This draft is not a binding contract. ReachPay’s legal team must replace it with approved terms that identify the operating entity, covered services, governing law and customer obligations.', sections: [['Service scope', 'Describe the actual services, eligibility, supported payment methods, provider dependencies, fees and service availability.'], ['Risk and support', 'Set out transaction handling, disputes, refunds, limitations, support channels and any applicable financial-service disclosures.'], ['Effective date and entity', 'Add the approved legal entity, registered address, governing law, effective date and version history.']] },
};
